### ISSUE TITLE
Advanced settings are not translatable

### ISSUE THREAD

**Issue by Atrafon** [cvzi/darkmodewallpaper#100]
Hi, I'm not know it issue or feature, but i'm not found this menu's text in files on Crowdin.![Screenshot_20221215-122330.png](https://user-images.githubusercontent.com/106192957/208147118-a3cd9422-cddd-47c4-9941-820ce4ab534e.png)
Thanks in advance for the explanation this moment.

**Comment by cvzi** [comment]
Thanks, I forgot about it. They should appear in crowdin in the next few hours
