### ISSUE TITLE
Is the License GPL-3.0-or-later?

### ISSUE THREAD

**Issue by linsui** [cvzi/darkmodewallpaper#11]
There ia no statement in the readme about the `or-later` but a badge says that the license is GPL-3.0-or-later. Is that intented? If then, could you please add the Standard License Header in the readme? Thanks!

**Comment by cvzi** [comment]
The source code files have the license header that states the "or later", I don't think it's necessary to add the header to the readme

**Comment by linsui** [comment]
Thanks!

**Comment by cvzi** [comment]
I see this is because of F-droid.

As far as I know Github cannot detect/show the "or later" part, it always shows "GPL-3.0 License"
![gpl3](https://user-images.githubusercontent.com/8470684/114025645-a282aa80-9875-11eb-961b-d7477d79352d.png)
Maybe that helps 🙄

**Comment by linsui** [comment]
Yep, GitHub does not care about that. Thanks!
