### ISSUE TITLE
Q: possible to scroll image to choose crop location?

### ISSUE THREAD

**Issue by adrian5** [cvzi/darkmodewallpaper#129]
Usually my wallpapers are wider than the phone screen. I only use a single home panel (nothing to swipe to left or right) so I scroll the wide image until I have a crop that I want (for the static wallpaper).

It seems that **DarkModeLiveWallpaper** always centers a given image. Is that the case or can I left/right scroll the imported image somehow?

**Comment by cvzi** [comment]
Currently there is no option to crop/zoom/move the image in the app. 
It always centers the image, you would have to crop the image with a another app beforehand.

**Comment by adrian5** [comment]
Got it, thanks.
