### ISSUE TITLE
Flash bug

### ISSUE THREAD

**Issue by Civilian-No-001** [cvzi/darkmodewallpaper#16]
When the screen is turned on, the home screen wallpaper will flash on the lock screen. 

Android 11

**Comment by Civilian-No-001** [comment]
@cvzi  well, nice update, turning off the effect makes me feel better, thanks your work.

In the latest version, I found that the flash will definitely reappear: after turning off the screen from the main screen, the wallpaper will flash when the screen is turned on quickly.

(The animate transition will invalid after installing for a while in this version, but it does not appear temporarily after reinstalling, i will open new issue if appear again).
(Default setting)

**Comment by cvzi** [comment]
Thanks for the details!

Does it only flash once or multiple flashes?

**Comment by Civilian-No-001** [comment]
Once, off - black - wallpaper(home) - black - lockscreen. 


Apr 30, 2021, 22:13 by ***@***.***:
