### ISSUE TITLE
Incorrect image shown in recents menu

### ISSUE THREAD

**Issue by Einlion** [cvzi/darkmodewallpaper#185]
![Screenshot_20240501-203056](https://github.com/cvzi/darkmodewallpaper/assets/65997318/88f323db-b04b-4b35-ad5b-e65f6685c8b7)

The wallpaper shown in recents screen is not the wallpaper being picked, instead its a default icon.
I am on Android 14 but this was present in 13 as well. I have tested applying other live wallpapers and they seem to work fine.

Thanks.

**Comment by cvzi** [comment]
I can't solve this anytime soon.

I don't have Android 13/14 on my phone. I tried to test it with Android emulator, but the Google Pixel that are available on the emulator don't show the wallpaper in the recent screens at all.

**Comment by cvzi** [comment]
Other live wallpapers are shown in the recent menu in a blurred way or normal?

And what phone do you have?

**Comment by Einlion** [comment]
They are shown in a blurred way. 
I have moto edge 30 ultra, Android 14
There's a chance this might be a moto laucher gotcha but I don't have a good idea on how live wallpapers work.

**Comment by cvzi** [comment]
Thanks. I'll take another look.

It is probably the Moto launcher that offers this feature of showing the wallpaper. I know the Moto Launcher customized the "recents screen" on Android 10 and this couldn't even be disabled, because it's part of the system. Even if you installed a third-party launcher, the Moto launcher was still handling the "recents screen" itself. Likely the same applies to Android 14.

**Comment by Einlion** [comment]
Hi, I believe the launcher is somehow using https://github.com/cvzi/darkmodewallpaper/blob/main/app/src/main/res/xml/wallpaper_info.xml#L25 as bg, tho i have no way to test and when im trying to generate local debug build it keeps failing.

**Comment by cvzi** [comment]
I have updated the repository, now the apk files are created in the Github actions. 
For example this is the last run: https://github.com/cvzi/darkmodewallpaper/actions/runs/9748487167 
At the bottom you can download the apk files.

I believe if you enable Github actions in your cloned repository [here](https://github.com/Einlion/live-wall-test/settings/actions) and update the Github action file to the version that I just created [gradleCI.yml](https://github.com/cvzi/darkmodewallpaper/blob/main/.github/workflows/gradleCI.yml),
then your repository should also generate the apk files, if you push a change.

**Comment by Einlion** [comment]
Thanks for the quick response! I tried the new version after those changes, looks file it's fixed now, I get a transparentish background as expected. I do not have full idea as to what that parameter actually is for and if changing it to transparent would cause any issue in hindsight.

**Comment by cvzi** [comment]
Any app can just request this thumbnail to use it, but the only use-case I know is the wallpaper selector. The thumbnail usually appears in the list of installed live wallpapers in the wallpaper selector.
Could be bug that moto launcher uses the wallpaper. Or maybe this app doesn't correctly deliver the actual wallpaper and the moto launcher uses the thumbnail as a "fallback" solution.

I wonder if it also works if you just remove the thumbnail.
Could you test it without it, like this:

```xml
<wallpaper xmlns:android="http://schemas.android.com/apk/res/android"
    android:description="@string/wallpaper_description"
    android:settingsActivity="com.github.cvzi.darkmodewallpaper.activity.MainActivity"
    android:showMetadataInPreview="true"
    android:supportsMultipleDisplays="true" />
```

Maybe also change the application id again to prevent any caching of the thumbnail

**Comment by cvzi** [comment]
@eddieofny 
I have create [two test apk](https://github.com/cvzi/darkmodewallpaper/releases/tag/v1.7.0) files for you. 

This file has no thumbnail: https://github.com/cvzi/darkmodewallpaper/releases/download/v1.7.0/no-thumbnail.apk

And this file has a transparent thumbnail: https://github.com/cvzi/darkmodewallpaper/releases/download/v1.7.0/transparent-thumbnail.apk

I would appreciate if you could test both of them and see if it solves the problem or if there is any difference. Thanks!

**Comment by eddieofny** [comment]
@cvzi Sorry this took me some time. I tested both APKs and they both work perfectly. Thanks!

**Comment by cvzi** [comment]
@eddieofny Thank you! I will include the solution in the normal version.

**Comment by Einlion** [comment]
I tried these as well, with no banner, it works fine but with transparent one, my wallpaper app crashes and i cant apply new wallpaper the normal way, though there are workarounds for that.

**Comment by cvzi** [comment]
Thanks! I did include the "no thumbnail" solution in the normal version 😀 

It will take a few days until F-Droid builds and publishes the new version.

**Comment by cvzi** [comment]
The new version 1.7.1 is now on F-Droid and in the Github releases (Google Play store will take a few hours or days). I would suggest to both of you to install that version again (you will lose the app settings unfortunately), so that you automatically get updates from F-Droid or Play Store .
