### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by ihatemakinganaccount** [cvzi/darkmodewallpaper#195]
I've started using this up this week and noticed that the average memory use over 3 hours, as well as immediate usage by the service, is 350MB. I think this is rather excessive.

I killed and restarted the app, and it went to ~130MB, which is still high imo. But it also goes up by 15-25MB every time the dark/light mode is switched.

Try:
1. Set the mode of wallpaper changing to "Follow system"
2. Kill the app and restart it
3. Enable the  phone's Android developer options
4. View the Running services
5. Observe the value of DarkModeLiveWallpaper
6. Switch between dark and light mode in Android (I use a quick settings tile)

The value of memory usage goes up and stays.

Also, I'm not using any effects (zoom, scroll, color overlay), and lock screen settings are not separate from wallpaper settings.

Anyway, thanks for the app. Cool little thing otherwise.

My phone: Motorola G32 w. CalyxOS 5.7.2 (Android 14)

**Comment by cvzi** [comment]
I'll look into it, maybe there is a memory leak somewhere

**Comment by cvzi** [comment]
I have found two memory leaks. I have resolved one of them. The other one is not relevant as far as I can tell because it seems to only occur when the wallpaper was set to the app and then changed to another live wallpaper.
It will take a few days until the next version is built and published.

Also as far as I understand, Android will only free memory if the overall free memory is low, so the amount of memory the app uses may be overstated if there is still free memory on the device left.

**Comment by ihatemakinganaccount** [comment]
Possibly, but the Running Services screen should be mostly accurate. Other resident apps I use are shown to take much less memory - right after reboot it's NTFY notification manager 7MB, KDE Connect 15MB, K-9 mail 40MB, Hypatia antivirus 50MB, Rethink DNS 50MB, HeliBoard keyboard 60MB, DMLW 96MB, so it's still a bit high from the start.

But okay, if it can stay at least at this level without ballooning... :)

Thanks!

**Comment by ihatemakinganaccount** [comment]
@cvzi it's still doing it, after I switch mode a few times, memory usage gets to pretty high levels :/

**Comment by cvzi** [comment]
I can't really reproduce this. On my phones and on the emulator, the memory goes up, but then it also goes down again.

**Comment by ihatemakinganaccount** [comment]
@cvzi ok I won't bug you about it, but I'm curious what memory usage do you see for this app under Running Services under dev options? Approximately

**Comment by cvzi** [comment]
About 75MB and when I switch dark/light mode it goes up to 100MB, after a few minutes it goes down to 75MB again.
If I keep switching dark/light mode it stays up at 100MB.

**Comment by cvzi** [comment]
About 50MB is just the libraries and the wallpaper service that I don't have any influence on. So I don't really want to

**Comment by ihatemakinganaccount** [comment]
Okay thx
