### ISSUE TITLE
[enchantment] LIVE WALLPAPER DOESN'T SHOW UP AFTER REBOOT unlike other live wallpaper apps 

### ISSUE THREAD

**Issue by Bobbydew1** [cvzi/darkmodewallpaper#204]
i just noticed that the live wallpaper doesn't show up in the lock screen after a reboot not a deal breaker for anyone, but it's a deal breaker for me(my stock wallpaper looks awful). I did try to reboot my phone with other live wallpaper apps; google pixel live wallpaper(port), dodle, pallax, and more and they all show up after a reboot.

**Comment by cvzi** [comment]
I am aware but unfortunately I don't know how it is possible

**Comment by cvzi** [comment]
I've looked at this again, and I think the problem is that the image files can't be loaded before unlocking the phone, because the files are still encrypted at that point. 
Maybe this can be solved by moving the files to the unencrypted storage of the phone.

**Comment by cvzi** [comment]
This should work now.

I have moved to images to the unencrypted storage and now they can be accessed after boot and before unlocking the phone
