### ISSUE TITLE
Can't install – "error analyzing package"

### ISSUE THREAD

**Issue by Martin5001** [cvzi/darkmodewallpaper#22]
I tried to install using the apk from both f-droid and GitHub but the Android package manager seems to not be able to install it.
I'm using Android 9, Samsung Galaxy J7

**Comment by Martin5001** [comment]
I just noticed it's Android 10 only, sorry, missed that

**Comment by cvzi** [comment]
Thank you for the translation!

**Comment by Martin5001** [comment]
You're welcome :)
