### ISSUE TITLE
Lockscreen text and notifications not changing colour according to wallpaper

### ISSUE THREAD

**Issue by SHolm3s** [cvzi/darkmodewallpaper#26]
Hey, Thanks for the app..its brilliant.
Just a minor hiccup. I'm using note 9 from Samsung and i have a very white wallpaper for the day and a dark grey one for the night
The app works perfectly to change the wallpaper, but the lockscreen text doesn't change from white to black duing day in order to be readable. 
I tried setting the wallpaper individually without the app and it changes colour. When i go to the lockscreen settings on the phone, with the app enabled, the wallpaper doesn't show up. Is the app putting the wallpaper in a different directory.? I don't know okay.. im not a developer..but this is an annoying issue...would be glad if you look into.

**Comment by cvzi** [comment]
Thanks for the report! It might be a bug in the app. 
The app sends the dominant colors of the wallpaper to the Android system and then the Android system decides which text color is best for that wallpaper. Maybe something is wrong and the app does not send the colors or maybe the wrong colors. I have never tested the process, so I am going to test it.

**Comment by cvzi** [comment]
This should work correctly now in the latest version
