### ISSUE TITLE
Cannot set separate wallpaper dark mode in Android 12

### ISSUE THREAD

**Issue by akuhl** [cvzi/darkmodewallpaper#27]
When I try to set a separate wallpaper for dark mode, a wallpaper picked with Google Photos is saved according to the toast message but neither set nor shown in preview.

version 1.1.2 on Android 12 Beta 3.1 with Google Pixel 5

**Comment by cvzi** [comment]
I just tried to run the app on the emulator and it does not work on Android 12. 
The app layout is wrong. Most of the buttons are not visible on Android 12. 
That should be easy to fix.

It is supposed to look like this:
<img height=400 src="https://raw.githubusercontent.com/cvzi/darkmodewallpaper/main/fastlane/metadata/android/en-US/images/phoneScreenshots/1_en-US.png"/>

**Comment by akuhl** [comment]
The app looks nothing like this on Android 12, the layout is fully broken:
![Uploading Screenshot_20210811-174530.png…]()

**Comment by akuhl** [comment]
Interestlingly, sharing a Wallpaper from Google Photos app to your app works for setting the wallpaper.

**Comment by akuhl** [comment]
Is there any new build available yet on F-Droid? AFAICS there is still build 1.1.2...

**Comment by cvzi** [comment]
They have not built it yet, not sure why it takes so long.

I have build it on my machine in the meantime. You can download the apk file from here if you want to test it:
https://github.com/cvzi/darkmodewallpaper/releases/tag/v1.1.6
You would have to uninstall the app first because this version is signed by my own key and the older version was signed by F-droid

**Comment by akuhl** [comment]
Layout is fixed with 1.1.6 your user signed build

**Comment by akuhl** [comment]
As commented on GitHub: All submitted bugs have been fixed with this
release. Thank you very much for your great work! 👍🏻

I reported two new issues with the release, a major and a minor one.

Cheers,
Andreas

-- 
Andreas Kuhl
Hofmannswaldaustr. 8
81739 München

Telefon: ‪+49.89.68094004‬
Mobil: +49.171.3154537

https://www.andreas-kuhl.de

cvzi ***@***.***> schrieb am Mo., 16. Aug. 2021, 15:00:
