### ISSUE TITLE
Material You color extraction freezes 

### ISSUE THREAD

**Issue by akuhl** [cvzi/darkmodewallpaper#28]
When using this app, Material You freezes on trying to extract wallpaper colors. Setting a fixed theme color does work.

I also saw this happening with other live wallpapers e.g. Material Island. Is this an Android 12 Beta 3.1 bug or is Android expecting any data via API that is not delivered? Google's own live wallpapers manage to pass the correct wallpaper colors to Material You.

**Comment by cvzi** [comment]
There was an error message in the log that said that the function `notifyColorsChanged()` should only be called once per minute. 
The app called it more than once per minute, but I don't know if that was the problem. Material You doesn't seem to work on the emulator yet so I cannot test it.

**Comment by akuhl** [comment]
I will give feedback as soon as the new build arrives on Google Play.

**Comment by akuhl** [comment]
No more freezes with 1.1.6 your user signed build, color detection works too
