### ISSUE TITLE
System-UI crash upon dark mode / light mode change

### ISSUE THREAD

**Issue by akuhl** [cvzi/darkmodewallpaper#30]
I have two different wallpapers for dark mode and light mode. If I set them with dark mode live wallpaper app and make the app my active live wallpaper, System-UI crashes upon mode change while the display is active. After the crash, only the wallpaper is shown whille all icons, status bar, widgets and gesture bar are gone. Shutting off the display via power key and switching it back on brings back the System-UI in the new mode.

Android 12 beta 4 on Google Pixel 5

**Comment by cvzi** [comment]
Could you check if it crashes when you manually change to dark/light mode or when Android automatically changes the mode due to sunrise/sunset (or both)

**Comment by akuhl** [comment]
Weird enough that I cannot reproduce this issue any longer while it used to happen each time before when switching the mode manually. During the last days, the crash seems to have disappeard.

I even set two now wallpapers but I cannot trigger the crash any longer.
