### ISSUE TITLE
Odd wallpaper preview in Android theme settings

### ISSUE THREAD

**Issue by akuhl** [cvzi/darkmodewallpaper#31]
This is a totally minor issue:

If I enter theme settings on Android 12, the preview of the dark mode live wallpaper shows the correct wallpaper but not fullscreen in the previed screens. Also, the wallpaper is shown twice per screen:

![edit_20210816160220](https://user-images.githubusercontent.com/863578/129576221-05f0f337-3339-4f86-aeee-6c1b555f61a6.jpg)

Android 12 beta 4 on Google Pixel 5

**Comment by cvzi** [comment]
I can see it on the emulator as well. At first the preview is distorted with wrong dimensions like in your image. But on the emulator it changes to the correct dimensions after a few seconds. 
Also the color detection does not seem to work in the preview.

This settings screen looks very different in the emulator although the emulator is also running Beta 4. The color section (I assume this is the Material You part?) is missing in the emulator. Did you have to change a setting or something like that to enable that?

![Screenshot of emulator](https://user-images.githubusercontent.com/8470684/130034868-6e3d0040-1adb-4120-a244-11dc18c4a413.png)

**Comment by akuhl** [comment]
Your settings screen looks like it used to look before Beta 3. From Beta 3 on (where the dynamic "Material You" coloring was enabled, the screen changed to what you can see on my screenshot (lockscreen and homescreen side by side).

The rendering is not updated after a few seconds on this screen, while the wallpaper is displayed correctly in the enlarged preview after clicking on the lockscreen oder homescreen:
![Screenshot_20210819-104738](https://user-images.githubusercontent.com/863578/130039691-96a7c90c-5456-4a73-866e-9c1a5f8f80ec.png)
![Screenshot_20210819-104748](https://user-images.githubusercontent.com/863578/130039696-df63f80f-590c-42a0-93e4-d353ed592f2f.png)

As I said: A real minor issue and probably not worth spending much effort on. Does not affect the functionality of your app in any way.
