### ISSUE TITLE
application size

### ISSUE THREAD

**Issue by TBog** [cvzi/darkmodewallpaper#42]
The apk has 8 mb. It's huge for a wallpaper application imho.
Maybe we can turn on `minifyEnabled` for release.

**Comment by cvzi** [comment]
Yes I can turn it on, not sure why I disabled it in the first place, might have been a copy/paste mistake

**Comment by cvzi** [comment]
The new apk file size is reduced by 67%
Now 2.6MB

![filesize](https://user-images.githubusercontent.com/8470684/166305143-d96e8c84-3d84-4705-9d40-f5cd52ae3a10.png)

**Comment by TBog** [comment]
I'll have a look at the dependencies tomorrow and if I don't see anything else we can remove I'll let you know we can close this.

Thanks for looking into this.
