### ISSUE TITLE
Option to blur the wallpaper

### ISSUE THREAD

**Issue by swapneelb** [cvzi/darkmodewallpaper#64]
Could you please add the option to blur the wallpaper like Muzei?
Some of the wallpapers I have are well suited if blurred.

**Comment by cvzi** [comment]
I can probably add that function, it doesn't seem to be complicated

For reference the Muzei class: 
https://github.com/muzei/muzei/blob/main/android-client-common/src/main/java/com/google/android/apps/muzei/util/ImageBlurrer.kt#L28

**Comment by swapneelb** [comment]
That would be a great addition, thanks for this.
Also, if possible, add the blur option to both, day and night mode, options.

**Comment by swapneelb** [comment]
I checked this out. Thank you for the feature.
However, the amount of blur at the maximum value isn't enough. Blur effect intensity should be more.
Also, this feature is hidden under contrast and brightness. Maybe you can add another option just for blur.

**Comment by cvzi** [comment]
I have increased the maximum value of the blur.
