### ISSUE TITLE
Full screen-to-Home Screen Wallpaper Display Bug

### ISSUE THREAD

**Issue by TheChaosRabbit** [cvzi/darkmodewallpaper#65]
Details: Pixel 5 | Android 12 | Pixel Launcher | 3-Button Navigation (No gestures)

I encountered a strange glitch when I was using the NewPipe app and exiting from full screen mode. When holding the phone horizontally and tapping the home button that appears while in full screen watching a video, the wallpaper will glitch and be displayed horizontally on the vertical home screen instead. I could only fix it by reselecting the image I use for the day or night background. (Whichever one I'm using at the time)

I did some more testing by enabling the "allow home screen rotation" option in system settings and found that the set image does not display properly.

Usually when using a normal home screen wallpaper and enabling the previously-mentioned setting and rotating the phone horizontally while on the home screen, the phone will take a horizontal cutout of the vertical orientation of the home screen picture being used and display that.

However, when rotating the phone while using this wallpaper changer, it rotates the wallpaper you chose and displays it horizontally instead. It also takes a second to load and will display incorrectly if you rotate the phone before it finishes loading.

**Comment by cvzi** [comment]
Thanks for the detailed report

**Comment by cvzi** [comment]
The current version [v1.3.1](https://github.com/cvzi/darkmodewallpaper/releases/tag/v1.3.1) has some improvements included. Can you please check if it makes a difference?

I am not sure if it helps with the rotating vs. cutout problem. If that problem persists, could you please post (or email me cuzi-android@openmail.cc) a screenshot and if possible the image file you're using as a wallpaper, so I can test with that.

**Comment by cvzi** [comment]
The newest version now has a workaround included. It doesn't prevent the glitch, but it should automatically resolve it after a few seconds.

**Comment by TheChaosRabbit** [comment]
Thanks for all the help! The wallpaper definitely works better now.
