### ISSUE TITLE
blurring night lockscreen does not work

### ISSUE THREAD

**Issue by khenderick** [cvzi/darkmodewallpaper#79]
It seems that blurring the night lock screen does not work. The day lockscreen can be blurred without problem. The issue is also visible in the preview.

Thanks for the awesome app.

**Comment by cvzi** [comment]
Fixed in version [v1.4.5](https://github.com/cvzi/darkmodewallpaper/releases/tag/v1.4.5)

**Comment by khenderick** [comment]
Thanks 😊
