### ISSUE TITLE
Daytime picker has limited file access

### ISSUE THREAD

**Issue by GundamPilotV** [cvzi/darkmodewallpaper#86]

**Comment by GundamPilotV** [comment]
https://user-images.githubusercontent.com/112837320/193948060-74ba48e9-904b-47b5-ae0e-9d7210be6785.mp4

**Comment by GundamPilotV** [comment]
Device name:Galaxy A71 5G
Model: SM-A716V
Manufacturer: samsung
Device a71xq
Board: lito
Hardware: qcom
Brand:samsung

**Comment by cvzi** [comment]
Thanks for the report!

**Comment by cvzi** [comment]
This seems to be the desired behavior of the new Android "photo picker":
https://developer.android.com/training/data-storage/shared/photopicker

I was not understanding that is limited when I added it, but that is a problem.

The night time picker is still the old picker, that is a bug, they should be the same.

There is also still the option to tap on the preview image and then "select image", that also still uses the old picker.

**Comment by cvzi** [comment]
In the new version, the day and night picker should be the same now. That is both have limited file access.

The option to tap on the preview image and then "select image" remains, and it still uses the old picker, although file access is limited as well on some phones.

I added a note to the README: https://github.com/cvzi/darkmodewallpaper#selecting-images
It explains that you can also share any image from another app to this app to set it as the wallpaper image. That seems to be the easiest way to circumvent the limited file access, without requiring a new permission.
