### ISSUE TITLE
White sliders in dark mode

### ISSUE THREAD

**Issue by Atrafon** [cvzi/darkmodewallpaper#96]
Hello, thanks for your app.
I don't know if you know, but the scrolling sliders in dark mode stay white like in light theme.

Light theme:
![Screenshot_20221211-211130.png](https://user-images.githubusercontent.com/106192957/206922040-35d0e1da-6e1e-41c9-b817-7112854a244c.png)
![Screenshot_20221211-211137.png](https://user-images.githubusercontent.com/106192957/206922051-96d83a9d-133f-4bd2-ac6c-35cd9555ac89.png)

Dark theme:
![Screenshot_20221211-212159.png](https://user-images.githubusercontent.com/106192957/206922071-c5c2ab12-a1a6-4d1c-aeb9-e71d7145941b.png)
![Screenshot_20221211-212204.png](https://user-images.githubusercontent.com/106192957/206922077-c163fea5-5da6-4ab0-a7c7-5e94b1263423.png)

I'm sorry if I wasted your time.

**Comment by cvzi** [comment]
Thanks!
I did not know 😂 

Don't know how to fix it, but I will try :)

**Comment by Atrafon** [comment]
Glad to hear.  Good luck fixing bugs.  The Russian translation on Crowdin has been updated. The year on the copyright will need to be updated soon. ![Screenshot_20221212-002354.png](https://user-images.githubusercontent.com/106192957/206929636-f073e6b8-07e2-45b6-81f2-e6b3336e89af.png)

**Comment by cvzi** [comment]
Are you makarrazin14 on crowdin?

**Comment by Atrafon** [comment]
Yes. I'm sorry if I reminded you so brazenly about translation.

**Comment by cvzi** [comment]
It is ok 👍

When I commit the changes from Crowdin to Github, I can use your Github name for the commit and then the changes in the files are connected to your Github account. Therefore I just wanted to know that it was really you

**Comment by Atrafon** [comment]
Glad to hear.  Always happy to help.
